### PR TITLE
Add multi repository support

### PR DESCRIPTION
**Pull request by inukshuk**
If I haven't missed anything this should enable us to support multiple repositories using the same Sheldon instance (with different templates for each repository).

I've already moved the templates into a `styles` sub-folder; to support locales you need to create a `locales` folder (the folder name must be the repository name!) and add the respective templates there.

Sheldon must have access rights to locales (which he does, since it's public) and locales on Travis CI must have been setup by the user who also setup styles (@rmzelle) for the authorization header check to pass.

To get this working (hopefully!):
* Merge the PR
* Add locales templates
* Create the webhook in the locales repository (same configuration as for styles)

### CODE REVIEW

**Comment by rmzelle** [comment]
Templates added in https://github.com/citation-style-language/Sheldon/commit/0418ce5bfa9f6769f1cd1d9818187c02b44adb84

**Comment by rmzelle** [comment]
Webhook added as well.

**Comment by adam3smith** [comment]
Thanks!

**Comment by rmzelle** [comment]
I created https://github.com/citation-style-language/locales/pull/128, and the initial PR creation post comes through, but the "build_passed" message hasn't appeared.

**Comment by inukshuk** [comment]
I forgot to mention to also enable the Travis CI webhook notification in `locales/.travis.yml`

**Comment by rmzelle** [comment]
Ah, thanks. I merged https://github.com/citation-style-language/locales/pull/129, and rebased https://github.com/citation-style-language/locales/pull/128 onto "master", and added a new commit to that PR, but I''m still not getting a pass/fail message.

**Comment by inukshuk** [comment]
Can you try again with a new PR -- there is nothing in Sheldon's log to suggest that it received a notification from Travis CI (if something is wrong with the auth header it should at least show up in the log, but I see only /pull_request requests but none at all at /build).

**Comment by inukshuk** [comment]
Hang on, the indentation of webhooks in .travis.yml is wrong!

**Comment by rmzelle** [comment]
Good catch! Things seem to work now! (see https://github.com/citation-style-language/locales/pull/128 )

**Pull request merged**
