### PR TITLE
Update pull_request_opened.md.erb

### PR DESCRIPTION
**Pull request by rmzelle**
@adam3smith, can you review? I fixed a grammar issue ("try get" > "try to get"), reduced the overall word count a little, and changed the last sentence to make it clearer people can write in any language they prefer.

### CODE REVIEW

**Comment by adam3smith** [comment]
Looks good to me. Personally I always liked the levity of the "human volunteers ... I will run some automated checks" so I'd leave that in unless you really don't like it.

**Comment by rmzelle** [comment]
Yeah, no strong feelings either way. I liked it too, but I think the current PR is a little clearer, which is especially important for non-native speakers. I think somebody mistook @csl-bot for a person once.

**Comment by adam3smith** [comment]
If you don't have strong feelings I'd leave it in. People are always going to be confused.

**Comment by rmzelle** [comment]
Take two. Feel free to merge.

**Comment by adam3smith** [comment]
(I couldn't squash this, not sure why)

**Comment by adam3smith** [comment]
Thanks!

**Comment by rmzelle** [comment]
Hmm, weird. I had no trouble squashing the other PR (although it only had one commit).

**Pull request merged**
